// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package responder_mocks

import (
	"net/netip"

	mock "github.com/stretchr/testify/mock"
)

// NewLimiter creates a new instance of Limiter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLimiter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Limiter {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &Limiter{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// Limiter is an autogenerated mock type for the Limiter type
type Limiter struct {
	mock.Mock
}

type Limiter_Expecter struct {
	mock *mock.Mock
}

func (_m *Limiter) EXPECT() *Limiter_Expecter {
	return &Limiter_Expecter{mock: &_m.Mock}
}

// Allow provides a mock function for the type Limiter
func (_mock *Limiter) Allow(addr netip.Addr) bool {
	ret := _mock.Called(addr)

	if len(ret) == 0 {
		panic("no return value specified for Allow")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(netip.Addr) bool); ok {
		r0 = returnFunc(addr)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Limiter_Allow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Allow'
type Limiter_Allow_Call struct {
	*mock.Call
}

// Allow is a helper method to define mock.On call
//   - addr netip.Addr
func (_e *Limiter_Expecter) Allow(addr any) *Limiter_Allow_Call {
	return &Limiter_Allow_Call{Call: _e.mock.On("Allow", addr)}
}

func (_c *Limiter_Allow_Call) Run(run func(addr netip.Addr)) *Limiter_Allow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 netip.Addr
		if args[0] != nil {
			arg0 = args[0].(netip.Addr)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Limiter_Allow_Call) Return(b bool) *Limiter_Allow_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Limiter_Allow_Call) RunAndReturn(run func(addr netip.Addr) bool) *Limiter_Allow_Call {
	_c.Call.Return(run)
	return _c
}

// SetGlobalRateLimit provides a mock function for the type Limiter
func (_mock *Limiter) SetGlobalRateLimit(n int) {
	_mock.Called(n)
	return
}

// Limiter_SetGlobalRateLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetGlobalRateLimit'
type Limiter_SetGlobalRateLimit_Call struct {
	*mock.Call
}

// SetGlobalRateLimit is a helper method to define mock.On call
//   - n int
func (_e *Limiter_Expecter) SetGlobalRateLimit(n any) *Limiter_SetGlobalRateLimit_Call {
	return &Limiter_SetGlobalRateLimit_Call{Call: _e.mock.On("SetGlobalRateLimit", n)}
}

func (_c *Limiter_SetGlobalRateLimit_Call) Run(run func(n int)) *Limiter_SetGlobalRateLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Limiter_SetGlobalRateLimit_Call) Return() *Limiter_SetGlobalRateLimit_Call {
	_c.Call.Return()
	return _c
}

func (_c *Limiter_SetGlobalRateLimit_Call) RunAndReturn(run func(n int)) *Limiter_SetGlobalRateLimit_Call {
	_c.Run(run)
	return _c
}

// SetPerIPRateLimit provides a mock function for the type Limiter
func (_mock *Limiter) SetPerIPRateLimit(n int) {
	_mock.Called(n)
	return
}

// Limiter_SetPerIPRateLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPerIPRateLimit'
type Limiter_SetPerIPRateLimit_Call struct {
	*mock.Call
}

// SetPerIPRateLimit is a helper method to define mock.On call
//   - n int
func (_e *Limiter_Expecter) SetPerIPRateLimit(n any) *Limiter_SetPerIPRateLimit_Call {
	return &Limiter_SetPerIPRateLimit_Call{Call: _e.mock.On("SetPerIPRateLimit", n)}
}

func (_c *Limiter_SetPerIPRateLimit_Call) Run(run func(n int)) *Limiter_SetPerIPRateLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Limiter_SetPerIPRateLimit_Call) Return() *Limiter_SetPerIPRateLimit_Call {
	_c.Call.Return()
	return _c
}

func (_c *Limiter_SetPerIPRateLimit_Call) RunAndReturn(run func(n int)) *Limiter_SetPerIPRateLimit_Call {
	_c.Run(run)
	return _c
}
