with-expecter: True
dir: "{{.InterfaceDirRelative}}/mocks"
mockname: "{{.InterfaceName}}"
outpkg: "{{.PackageName}}_mocks"
filename: "{{.InterfaceName}}.go"
packages:
  github.com/hexsans/hexmagnet/internal/classifier:
    interfaces:
      LocalSearch:
  github.com/hexsans/hexmagnet/internal/protocol/dht/ktable:
    interfaces:
      Table:
  github.com/hexsans/hexmagnet/internal/protocol/dht/responder:
    interfaces:
      Limiter:
  github.com/hexsans/hexmagnet/internal/tmdb:
    interfaces:
      Client:

