enum ContentType {
  movie
  tv_show
  music
  ebook
  comic
  audiobook
  game
  software
  other
  unknown
  adult
}

enum FacetLogic {
  and
  or
}

enum FileType {
  archive
  audio
  data
  document
  image
  software
  subtitles
  video
}

enum Language {
  af
  ar
  az
  be
  bg
  bs
  ca
  ce
  co
  cs
  cy
  da
  de
  el
  en
  es
  et
  eu
  fa
  fi
  fr
  he
  hi
  hr
  hu
  hy
  id
  is
  it
  ja
  ka
  ko
  ku
  lt
  lv
  mi
  mk
  ml
  mn
  ms
  mt
  nl
  no
  pl
  pt
  ro
  ru
  sa
  sk
  sl
  sm
  so
  sr
  sv
  ta
  th
  tr
  uk
  vi
  yi
  zh
  zu
}

enum TorrentContentOrderByField {
  relevance
  created_at
  updated_at
  size
  files_count
  seeders
  leechers
  name
  info_hash
}

enum TorrentSearchOrderByField {
  relevance
  created_at
  updated_at
  size
  files_count
  seeders
  leechers
  name
  info_hash
}

enum SortDirection {
  asc
  desc
}

enum TorrentFilesOrderByField {
  index
  extension
  size
}
