type Torrent {
  infoHash: Hash20!
  name: String!
  size: Uint64!
  hasFilesInfo: Boolean!
  singleFile: Boolean
  filesCount: Int
  fileType: FileType
  fileTypes: [FileType!]
  files: [TorrentFile!]
  seeders: Int
  leechers: Int
  magnetUri: String!
  createdAt: DateTime!
  updatedAt: DateTime!
}

type TorrentFile {
  infoHash: Hash20!
  index: Int!
  pathParts: [String!]!
  extension: String
  fileType: FileType
  size: Uint64!
  createdAt: DateTime!
  updatedAt: DateTime!
}

type TorrentSearch {
  infoHash: Hash20!
  torrent: Torrent!
  contentType: ContentType
  contentSource: String
  contentId: String
  content: Content
  title: String!
  languages: [LanguageInfo!]
  seeders: Int
  leechers: Int
  createdAt: DateTime!
  updatedAt: DateTime!
}

type LanguageInfo {
  id: String!
  name: String!
}

type ExternalLink {
  source: String!
  url: String!
}

type Content {
  type: ContentType!
  source: String!
  id: String!
  title: String!
  releaseDate: Date
  adult: Boolean
  overview: String
  popularity: Float
  voteAverage: Float
  voteCount: Int
  externalLinks: [ExternalLink!]!
  createdAt: DateTime!
  updatedAt: DateTime!
}
