type Query {
  version: String!
  workers: WorkersQuery!
  health: HealthQuery!
  torrent: TorrentQuery!
  torrentSearch: TorrentSearchQuery!
  queue: QueueQuery!
  retryQueue: RetryQueueQuery!
  reindexStatus: ReindexProgress!
  reclassifyStatus: ReclassifyProgress!
}

type TorrentQuery {
  files(input: TorrentFilesQueryInput!): TorrentFilesQueryResult!
  metrics(input: TorrentMetricsQueryInput!): TorrentMetricsQueryResult!
}

type TorrentSearchQuery {
  search(input: TorrentSearchQueryInput!): TorrentSearchResult!
}

type Worker {
  key: String!
  started: Boolean!
}

type WorkersListAllQueryResult {
  workers: [Worker!]!
}

type WorkersQuery {
  listAll: WorkersListAllQueryResult!
}

enum HealthStatus {
  unknown
  inactive
  up
  down
}

type HealthCheck {
  key: String!
  status: HealthStatus!
  timestamp: DateTime!
  error: String
}

type HealthQuery {
  status: HealthStatus!
  checks: [HealthCheck!]!
}
