enum QueueJobStatus {
  pending
  processed
  failed
  retry
}

enum QueueJobsOrderByField {
  createdAt
  ranAt
  priority
}

input QueueMetricsQueryInput {
  bucketDuration: MetricsBucketDuration!
  queues: [String!]
  statuses: [QueueJobStatus!]
  startTime: DateTime
  endTime: DateTime
}

input QueueJobQueueFacetInput {
  values: [String!]!
  logic: FacetLogic!
}

input QueueJobsOrderByInput {
  field: QueueJobsOrderByField!
  descending: Boolean
}

input QueueJobsQueryInput {
  queues: QueueJobQueueFacetInput
  orderBy: QueueJobsOrderByInput
  limit: Int
  offset: Int
}

type QueueMetricsBucket {
  queue: String!
  status: QueueJobStatus!
  createdAtBucket: DateTime!
  ranAtBucket: DateTime
  count: Int!
  latency: Duration
}

type QueueMetricsQueryResult {
  buckets: [QueueMetricsBucket!]!
}

type QueueJob {
  id: String!
  queue: String!
  payload: String!
  createdAt: DateTime!
}

type QueueJobQueueAgg {
  value: String!
  label: String!
  count: Int!
}

type QueueJobsAggregations {
  queue: [QueueJobQueueAgg!]
}

type QueueJobsQueryResult {
  totalCount: Int!
  hasNextPage: Boolean
  items: [QueueJob!]!
  aggregations: QueueJobsAggregations!
}

type QueueQuery {
  metrics(input: QueueMetricsQueryInput!): QueueMetricsQueryResult!
  jobs(input: QueueJobsQueryInput!): QueueJobsQueryResult!
}


