package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"

	"github.com/hexsans/hexmagnet/internal/configmgr"
	"github.com/hexsans/hexmagnet/internal/gql/gqlmodel/gen"
	"github.com/hexsans/hexmagnet/internal/torznab"
	"github.com/hexsans/hexmagnet/internal/webhook"
)

// UpdateConfig is the resolver for the updateConfig field.
func (r *mutationResolver) UpdateConfig(ctx context.Context, input gen.ConfigInput) (gen.Config, error) {
	data, err := readConfigFile(r.ConfigFilePath)
	if err != nil {
		return gen.Config{}, fmt.Errorf("read config: %w", err)
	}

	if v, ok := input.Dht.ValueOK(); ok && v != nil {
		if err := applyDHTInput(data, *v); err != nil {
			return gen.Config{}, fmt.Errorf("dht: %w", err)
		}
	}

	if v, ok := input.Server.ValueOK(); ok && v != nil {
		if err := applyServerInput(data, *v); err != nil {
			return gen.Config{}, fmt.Errorf("server: %w", err)
		}
	}

	if v, ok := input.Classifier.ValueOK(); ok && v != nil {
		if err := applyClassifierInput(data, *v); err != nil {
			return gen.Config{}, fmt.Errorf("classifier: %w", err)
		}
	}

	if v, ok := input.Storage.ValueOK(); ok && v != nil {
		if err := applyStorageInput(data, *v); err != nil {
			return gen.Config{}, fmt.Errorf("storage: %w", err)
		}
	}

	if v, ok := input.Torznab.ValueOK(); ok && v != nil {
		if err := applyTorznabInput(data, *v); err != nil {
			return gen.Config{}, fmt.Errorf("torznab: %w", err)
		}
	}

	if v, ok := input.Webhooks.ValueOK(); ok && v != nil {
		if err := applyWebhooksInput(data, *v); err != nil {
			return gen.Config{}, fmt.Errorf("webhooks: %w", err)
		}
	}

	// Pre-flight validation: probes and structural checks run against the
	// merged config. On failure nothing is written or applied, so the service
	// keeps running with the old values.
	validator := r.ConfigValidator
	if validator == nil {
		validator = newConfigValidator()
	}
	if err := validator.Validate(ctx, input, data); err != nil {
		return gen.Config{}, fmt.Errorf("config validation failed: %w", err)
	}

	if err := writeConfigFile(r.ConfigFilePath, data); err != nil {
		return gen.Config{}, fmt.Errorf("write config: %w", err)
	}

	// Phase 1: Update in-memory Resolver config fields from the saved data.
	if _, ok := input.Dht.ValueOK(); ok {
		if dhtRaw, ok := data["dht"]; ok {
			dhtMap, dhtOk := dhtRaw.(map[string]any)
			if dhtOk {
				if err := reloadConfigSection(dhtMap, &r.DhtCfg); err != nil {
					r.Logger.Warnw("failed to reload dht config", "error", err)
				}
				if reqRaw, ok := dhtMap["requester"]; ok {
					if err := reloadConfigSection(reqRaw, &r.DHTRequesterCfg); err != nil {
						r.Logger.Warnw("failed to reload dht requester config", "error", err)
					}
				}
			}
		}
	}
	if _, ok := input.Server.ValueOK(); ok {
		if raw, ok := data["server"]; ok {
			if rawMap, ok := raw.(map[string]any); ok {
				if err := reloadConfigSection(rawMap, &r.ServerCfg); err != nil {
					r.Logger.Warnw("failed to reload server config", "error", err)
				}
			}
		}
	}
	if _, ok := input.Classifier.ValueOK(); ok {
		if raw, ok := data["classifier"]; ok {
			if rawMap, ok := raw.(map[string]any); ok {
				if err := reloadConfigSection(rawMap, &r.ClassifierCfg); err != nil {
					r.Logger.Warnw("failed to reload classifier config", "error", err)
				}
			}
		}
	}
	if _, ok := input.Storage.ValueOK(); ok {
		if raw, ok := data["storage"]; ok {
			if rawMap, ok := raw.(map[string]any); ok {
				if pgRaw, ok := rawMap["postgres"]; ok {
					if err := reloadConfigSection(pgRaw, &r.PostgresCfg); err != nil {
						r.Logger.Warnw("failed to reload postgres config", "error", err)
					}
				}
				if srRaw, ok := rawMap["search"]; ok {
					if err := reloadConfigSection(srRaw, &r.SearchCfg); err != nil {
						r.Logger.Warnw("failed to reload search config", "error", err)
					}
				}
				if qRaw, ok := rawMap["queue"]; ok {
					if err := reloadConfigSection(qRaw, &r.QueueCfg); err != nil {
						r.Logger.Warnw("failed to reload queue config", "error", err)
					}
				}
			}
		}
	}

	if _, ok := input.Torznab.ValueOK(); ok {
		if raw, ok := data["torznab"]; ok {
			if rawMap, ok := raw.(map[string]any); ok {
				// Reset first: mapstructure merges into existing maps
				// (e.g. Headers), which would resurrect removed entries.
				r.TorznabCfg = torznab.NewDefaultConfig()
				if err := reloadConfigSection(rawMap, &r.TorznabCfg); err != nil {
					r.Logger.Warnw("failed to reload torznab config", "error", err)
				}
			}
		}
	}
	if _, ok := input.Webhooks.ValueOK(); ok {
		if raw, ok := data["webhooks"]; ok {
			if rawMap, ok := raw.(map[string]any); ok {
				// Reset first: mapstructure merges into existing maps
				// (e.g. Headers), which would resurrect removed entries.
				r.WebhooksCfg = webhook.NewDefaultConfig()
				if err := reloadConfigSection(rawMap, &r.WebhooksCfg); err != nil {
					r.Logger.Warnw("failed to reload webhooks config", "error", err)
				}
			}
		}
	}

	// Build snapshot from reloaded config structs and dispatch to subscribers.
	if r.ConfigManager != nil {
		snap := &configmgr.Snapshot{
			DHTRequester: r.DHTRequesterCfg,
			DHT:          r.DhtCfg,
			Server:       r.ServerCfg,
			Classifier:   r.ClassifierCfg,
			Postgres:     r.PostgresCfg,
			Queue:        r.QueueCfg,
			Search:       r.SearchCfg,
			Torznab:      r.TorznabCfg,
			Webhooks:     r.WebhooksCfg,
			RetryQueue:   r.RetryQueueCfg,
		}
		if err := r.ConfigManager.Apply(ctx, snap); err != nil {
			r.Logger.Warnw("failed to apply config update", "error", err)
			return gen.Config{}, fmt.Errorf("config saved but some live components failed to apply: %w", err)
		}
	}

	return gen.Config{
		Dht:        configToDHT(r.DhtCfg),
		Server:     configToServer(r.ServerCfg),
		Classifier: configToClassifier(r.ClassifierCfg),
		Storage:    configToStorage(r.PostgresCfg, r.SearchCfg, r.QueueCfg),
		Torznab:    configToTorznab(r.TorznabCfg),
		Webhooks:   configToWebhooks(r.WebhooksCfg),
	}, nil
}

// Config is the resolver for the config field.
func (r *queryResolver) Config(ctx context.Context) (gen.Config, error) {
	dht := configToDHT(r.DhtCfg)
	dht.Requester = configToDHTRequester(r.DHTRequesterCfg)
	return gen.Config{
		Dht:        dht,
		Server:     configToServer(r.ServerCfg),
		Classifier: configToClassifier(r.ClassifierCfg),
		Storage:    configToStorage(r.PostgresCfg, r.SearchCfg, r.QueueCfg),
		Torznab:    configToTorznab(r.TorznabCfg),
		Webhooks:   configToWebhooks(r.WebhooksCfg),
	}, nil
}
