package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/hexsans/hexmagnet/internal/gql/gqlmodel"
	"github.com/hexsans/hexmagnet/internal/model"
)

// DhtCrawler is the resolver for the dhtCrawler field.
func (r *queryResolver) DhtCrawler(ctx context.Context) (gqlmodel.DhtCrawlerStatus, error) {
	reason := ""
	if r.JobControl != nil {
		reason = r.JobControl.Reason()
	}

	paused := reason != ""

	pauseReason := model.NullString{}
	if paused {
		pauseReason = model.NewNullString(reason)
	}

	return gqlmodel.DhtCrawlerStatus{
		Runtime:     r.DhtCrawlerRuntime,
		DB:          r.DB,
		Paused:      paused,
		PauseReason: pauseReason,
	}, nil
}
