package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/hexsans/hexmagnet/internal/gql/gqlmodel"
)

// DhtCrawler is the resolver for the dhtCrawler field.
func (r *queryResolver) DhtCrawler(ctx context.Context) (gqlmodel.DhtCrawlerStatus, error) {
	return gqlmodel.DhtCrawlerStatus{
		Runtime: r.DhtCrawlerRuntime,
		DB:      r.DB,
	}, nil
}
