package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/hexsans/hexmagnet/internal/gql"
	"github.com/hexsans/hexmagnet/internal/gql/gqlmodel"
	"github.com/hexsans/hexmagnet/internal/gql/gqlmodel/gen"
	"github.com/hexsans/hexmagnet/internal/processor"
	"github.com/hexsans/hexmagnet/internal/processor/enrich/indexer"
	"github.com/hexsans/hexmagnet/internal/queue/kafka"
)

// Torrent is the resolver for the torrent field.
func (r *mutationResolver) Torrent(ctx context.Context) (gqlmodel.TorrentMutation, error) {
	return gqlmodel.TorrentMutation{DB: r.DB, ESClient: r.ES(), Embedder: r.EM()}, nil
}

// RetryQueue is the resolver for the retryQueue field.
func (r *mutationResolver) RetryQueue(ctx context.Context) (gqlmodel.RetryQueueMutation, error) {
	return gqlmodel.RetryQueueMutation{Queue: r.RetryQueueSvc}, nil
}

// Reprocess is the resolver for the reprocess field.
func (r *torrentMutationResolver) Reprocess(ctx context.Context, obj *gqlmodel.TorrentMutation, input gen.TorrentReprocessInput) (*string, error) {
	params := processor.MessageParams{
		InfoHashes: input.InfoHashes,
	}

	if r, ok := input.ClassifierRematch.ValueOK(); ok && *r {
		params.ClassifyMode = processor.ClassifyModeRematch
	}

	if ct, ok := input.ContentType.ValueOK(); ok && ct != nil {
		params.ContentType = string(*ct)
	}

	key := ""
	if len(params.InfoHashes) > 0 {
		key = params.InfoHashes[0].String()
	}

	r.Producer.Produce(kafka.TopicProcessTorrent, key, params)

	return nil, nil
}

// ReindexToElasticsearch is the resolver for the reindexToElasticsearch field.
func (r *torrentMutationResolver) ReindexToElasticsearch(ctx context.Context, obj *gqlmodel.TorrentMutation) (gen.ReindexProgress, error) {
	if obj.ESClient == nil {
		return gen.ReindexProgress{Done: true, Error: ptr("elasticsearch not configured")}, nil
	}
	if obj.Embedder == nil {
		return gen.ReindexProgress{Done: true, Error: ptr("embedding not configured")}, nil
	}

	searchCfg := r.Resolver.SearchCfg
	if r.Resolver.ConfigManager != nil {
		searchCfg = r.Resolver.ConfigManager.Get().Search
	}

	dims := searchCfg.Elasticsearch.Embedding.Dimensions
	if dims <= 0 {
		dims = 1024
	}

	if err := r.Resolver.ReindexTracker.Start(
		context.Background(),
		obj.ESClient,
		obj.Embedder,
		obj.DB,
		dims,
		searchCfg.MaxSearchFiles,
		indexer.Fingerprint(searchCfg),
		false,
		r.Resolver.Logger,
	); err != nil {
		return gen.ReindexProgress{Done: true, Error: ptr(err.Error())}, nil
	}

	status := r.Resolver.ReindexTracker.Progress()

	return reindexProgressGQL(status), nil
}

// ReclassifyTorrents is the resolver for the reclassifyTorrents field.
func (r *torrentMutationResolver) ReclassifyTorrents(ctx context.Context, obj *gqlmodel.TorrentMutation) (gen.ReclassifyProgress, error) {
	classifierCfg := r.Resolver.ClassifierCfg
	if r.Resolver.ConfigManager != nil {
		classifierCfg = r.Resolver.ConfigManager.Get().Classifier
	}

	if err := r.Resolver.ReclassifyTracker.Start(
		context.Background(),
		r.Resolver.Processor,
		r.Resolver.DB,
		processor.Fingerprint(classifierCfg),
		r.Resolver.Logger,
	); err != nil {
		return gen.ReclassifyProgress{Done: true, Error: ptr(err.Error())}, nil
	}

	status := r.Resolver.ReclassifyTracker.Progress()

	return reclassifyProgressGQL(status), nil
}

// DiscardReindexProgress is the resolver for the discardReindexProgress field.
func (r *torrentMutationResolver) DiscardReindexProgress(ctx context.Context, obj *gqlmodel.TorrentMutation) (gen.ReindexProgress, error) {
	if err := r.Resolver.ReindexTracker.Discard(ctx); err != nil {
		return gen.ReindexProgress{Done: true, Error: ptr(err.Error())}, nil
	}

	return reindexProgressGQL(r.Resolver.ReindexTracker.Progress()), nil
}

// DiscardReclassifyProgress is the resolver for the discardReclassifyProgress field.
func (r *torrentMutationResolver) DiscardReclassifyProgress(ctx context.Context, obj *gqlmodel.TorrentMutation) (gen.ReclassifyProgress, error) {
	if err := r.Resolver.ReclassifyTracker.Discard(ctx); err != nil {
		return gen.ReclassifyProgress{Done: true, Error: ptr(err.Error())}, nil
	}

	return reclassifyProgressGQL(r.Resolver.ReclassifyTracker.Progress()), nil
}

// Mutation returns gql.MutationResolver implementation.
func (r *Resolver) Mutation() gql.MutationResolver { return &mutationResolver{r} }

// TorrentMutation returns gql.TorrentMutationResolver implementation.
func (r *Resolver) TorrentMutation() gql.TorrentMutationResolver { return &torrentMutationResolver{r} }

type (
	mutationResolver        struct{ *Resolver }
	torrentMutationResolver struct{ *Resolver }
)
