package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/hexsans/hexmagnet/internal/gql"
	"github.com/hexsans/hexmagnet/internal/gql/gqlmodel"
	"github.com/hexsans/hexmagnet/internal/gql/gqlmodel/gen"
	"github.com/hexsans/hexmagnet/internal/processor"
	"github.com/hexsans/hexmagnet/internal/queue/kafka"
)

// Torrent is the resolver for the torrent field.
func (r *mutationResolver) Torrent(ctx context.Context) (gqlmodel.TorrentMutation, error) {
	return gqlmodel.TorrentMutation{DB: r.DB, ESClient: r.ES(), Embedder: r.EM()}, nil
}

// RetryQueue is the resolver for the retryQueue field.
func (r *mutationResolver) RetryQueue(ctx context.Context) (gqlmodel.RetryQueueMutation, error) {
	return gqlmodel.RetryQueueMutation{Queue: r.RetryQueueSvc}, nil
}

// Reprocess is the resolver for the reprocess field.
func (r *torrentMutationResolver) Reprocess(ctx context.Context, obj *gqlmodel.TorrentMutation, input gen.TorrentReprocessInput) (*string, error) {
	params := processor.MessageParams{
		InfoHashes: input.InfoHashes,
	}

	if r, ok := input.ClassifierRematch.ValueOK(); ok && *r {
		params.ClassifyMode = processor.ClassifyModeRematch
	}

	if ct, ok := input.ContentType.ValueOK(); ok && ct != nil {
		params.ContentType = string(*ct)
	}

	key := ""
	if len(params.InfoHashes) > 0 {
		key = params.InfoHashes[0].String()
	}

	r.Producer.Produce(kafka.TopicProcessTorrent, key, params)

	return nil, nil
}

// ReindexToElasticsearch is the resolver for the reindexToElasticsearch field.
func (r *torrentMutationResolver) ReindexToElasticsearch(ctx context.Context, obj *gqlmodel.TorrentMutation) (gen.ReindexProgress, error) {
	if obj.ESClient == nil {
		return gen.ReindexProgress{Done: true, Error: ptr("elasticsearch not configured")}, nil
	}
	if obj.Embedder == nil {
		return gen.ReindexProgress{Done: true, Error: ptr("embedding not configured")}, nil
	}

	dims := r.Resolver.SearchCfg.Elasticsearch.Embedding.Dimensions
	if dims <= 0 {
		dims = 1024
	}

	if err := r.Resolver.ReindexTracker.Start(
		context.Background(),
		obj.ESClient,
		obj.Embedder,
		obj.DB,
		dims,
		r.Resolver.SearchCfg.MaxSearchFiles,
		r.Resolver.Logger,
	); err != nil {
		return gen.ReindexProgress{Done: true, Error: ptr(err.Error())}, nil
	}

	total, indexed, done, running, errMsg := r.Resolver.ReindexTracker.Progress()
	return gen.ReindexProgress{
		Total:   total,
		Indexed: indexed,
		Done:    done,
		Running: running,
		Error:   nilStr(errMsg),
	}, nil
}

// Mutation returns gql.MutationResolver implementation.
func (r *Resolver) Mutation() gql.MutationResolver { return &mutationResolver{r} }

// TorrentMutation returns gql.TorrentMutationResolver implementation.
func (r *Resolver) TorrentMutation() gql.TorrentMutationResolver { return &torrentMutationResolver{r} }

type (
	mutationResolver        struct{ *Resolver }
	torrentMutationResolver struct{ *Resolver }
)
