package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"sort"

	"github.com/hexsans/hexmagnet/internal/gql"
	"github.com/hexsans/hexmagnet/internal/gql/gqlmodel"
	"github.com/hexsans/hexmagnet/internal/gql/gqlmodel/gen"
	"github.com/hexsans/hexmagnet/internal/health"
	"github.com/hexsans/hexmagnet/internal/queue"
	dbsearch "github.com/hexsans/hexmagnet/internal/search"
	"github.com/hexsans/hexmagnet/internal/version"
)

// Version is the resolver for the version field.
func (r *queryResolver) Version(ctx context.Context) (string, error) {
	return version.GitTag, nil
}

// Workers is the resolver for the workers field.
func (r *queryResolver) Workers(ctx context.Context) (gen.WorkersQuery, error) {
	var workers []gen.Worker
	for _, w := range r.Resolver.Workers.Workers() {
		workers = append(workers, gen.Worker{
			Key:     w.Key(),
			Started: w.Started(),
		})
	}

	return gen.WorkersQuery{
		ListAll: gen.WorkersListAllQueryResult{
			Workers: workers,
		},
	}, nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (gen.HealthQuery, error) {
	transformHealthCheckStatus := func(s health.AvailabilityStatus) gen.HealthStatus {
		switch s {
		case health.StatusInactive:
			return gen.HealthStatusInactive
		case health.StatusDown:
			return gen.HealthStatusDown
		case health.StatusUp:
			return gen.HealthStatusUp
		default:
			return gen.HealthStatusUnknown
		}
	}
	check := r.Checker.Check(ctx)
	checks := make([]gen.HealthCheck, 0, len(check.Details))

	for k, v := range check.Details {
		if v.Status == health.StatusInactive {
			continue
		}

		var err *string

		if v.Error != nil {
			err = new(v.Error.Error())
		}

		checks = append(checks, gen.HealthCheck{
			Key:       k,
			Status:    transformHealthCheckStatus(v.Status),
			Timestamp: v.Timestamp,
			Error:     err,
		})
	}

	sort.Slice(checks, func(i, j int) bool {
		return checks[i].Key < checks[j].Key
	})

	result := gen.HealthQuery{
		Status: transformHealthCheckStatus(check.Status),
		Checks: checks,
	}

	return result, nil
}

// Torrent is the resolver for the torrent field.
func (r *queryResolver) Torrent(ctx context.Context) (gqlmodel.TorrentQuery, error) {
	var s dbsearch.Search
	if r.SearchRuntime != nil {
		s = r.SearchRuntime.Search.Get()
	}
	return gqlmodel.TorrentQuery{
		DB:                   r.DB,
		Search:               s,
		TorrentMetricsClient: r.TorrentMetricsClient,
	}, nil
}

// TorrentSearch is the resolver for the torrentSearch field.
func (r *queryResolver) TorrentSearch(ctx context.Context) (gqlmodel.TorrentSearchQuery, error) {
	var s dbsearch.Search
	if r.SearchRuntime != nil {
		s = r.SearchRuntime.Search.Get()
	}
	return gqlmodel.TorrentSearchQuery{
		Svc:    s,
		Logger: r.Logger,
	}, nil
}

// Queue is the resolver for the queue field.
func (r *queryResolver) Queue(ctx context.Context) (gqlmodel.QueueQuery, error) {
	var qm queue.Manager
	if r.QueueRuntime != nil {
		qm = r.QueueRuntime.DynamicManager()
	}
	return gqlmodel.QueueQuery{
		QueueManager: qm,
	}, nil
}

// ReindexStatus is the resolver for the reindexStatus field.
func (r *queryResolver) ReindexStatus(ctx context.Context) (gen.ReindexProgress, error) {
	total, indexed, done, running, errMsg := r.Resolver.ReindexTracker.Progress()
	return gen.ReindexProgress{Total: total, Indexed: indexed, Done: done, Running: running, Error: nilStr(errMsg)}, nil
}

// Files is the resolver for the files field.
func (r *torrentQueryResolver) Files(ctx context.Context, obj *gqlmodel.TorrentQuery, input gqlmodel.TorrentFilesQueryInput) (gqlmodel.TorrentFilesQueryResult, error) {
	var s dbsearch.Search
	if r.SearchRuntime != nil {
		s = r.SearchRuntime.Search.Get()
	}
	return gqlmodel.SearchTorrentFiles(ctx, s, input, r.Logger)
}

// Query returns gql.QueryResolver implementation.
func (r *Resolver) Query() gql.QueryResolver { return &queryResolver{r} }

// TorrentQuery returns gql.TorrentQueryResolver implementation.
func (r *Resolver) TorrentQuery() gql.TorrentQueryResolver { return &torrentQueryResolver{r} }

type (
	queryResolver        struct{ *Resolver }
	torrentQueryResolver struct{ *Resolver }
)
