package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/hexsans/hexmagnet/internal/gql"
	"github.com/hexsans/hexmagnet/internal/gql/gqlmodel/gen"
	"github.com/hexsans/hexmagnet/internal/metrics/queuemetrics"
)

// Status is the resolver for the status field.
func (r *queueMetricsBucketResolver) Status(ctx context.Context, obj *queuemetrics.Bucket) (gen.QueueJobStatus, error) {
	return gen.QueueJobStatus(obj.Status), nil
}

// QueueMetricsBucket returns gql.QueueMetricsBucketResolver implementation.
func (r *Resolver) QueueMetricsBucket() gql.QueueMetricsBucketResolver {
	return &queueMetricsBucketResolver{r}
}

type queueMetricsBucketResolver struct{ *Resolver }
