package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/hexsans/hexmagnet/internal/gql"
	"github.com/hexsans/hexmagnet/internal/gql/gqlmodel"
)

// Clear is the resolver for the clear field.
func (r *retryQueueMutationResolver) Clear(ctx context.Context, obj *gqlmodel.RetryQueueMutation) (*string, error) {
	return nil, obj.Clear(ctx)
}

// RetryQueueMutation returns gql.RetryQueueMutationResolver implementation.
func (r *Resolver) RetryQueueMutation() gql.RetryQueueMutationResolver {
	return &retryQueueMutationResolver{r}
}

type retryQueueMutationResolver struct{ *Resolver }
