// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blocked_info_hash.sql

package db

import (
	"context"
)

const CountBlockedInfoHashes = `-- name: CountBlockedInfoHashes :one
SELECT COUNT(*) FROM blocked_info_hash
`

func (q *Queries) CountBlockedInfoHashes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, CountBlockedInfoHashes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const DeleteBlockedInfoHash = `-- name: DeleteBlockedInfoHash :exec
DELETE FROM blocked_info_hash WHERE info_hash = $1
`

func (q *Queries) DeleteBlockedInfoHash(ctx context.Context, infoHash string) error {
	_, err := q.db.Exec(ctx, DeleteBlockedInfoHash, infoHash)
	return err
}

const GetBlockedInfoHash = `-- name: GetBlockedInfoHash :one
SELECT info_hash, reason, blocked_at FROM blocked_info_hash WHERE info_hash = $1
`

func (q *Queries) GetBlockedInfoHash(ctx context.Context, infoHash string) (BlockedInfoHash, error) {
	row := q.db.QueryRow(ctx, GetBlockedInfoHash, infoHash)
	var i BlockedInfoHash
	err := row.Scan(&i.InfoHash, &i.Reason, &i.BlockedAt)
	return i, err
}

const GetBlockedInfoHashes = `-- name: GetBlockedInfoHashes :many
SELECT info_hash FROM blocked_info_hash WHERE info_hash = ANY($1::text[])
`

func (q *Queries) GetBlockedInfoHashes(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, GetBlockedInfoHashes, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var info_hash string
		if err := rows.Scan(&info_hash); err != nil {
			return nil, err
		}
		items = append(items, info_hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListBlockedInfoHashes = `-- name: ListBlockedInfoHashes :many
SELECT info_hash, reason, blocked_at FROM blocked_info_hash ORDER BY blocked_at DESC
`

func (q *Queries) ListBlockedInfoHashes(ctx context.Context) ([]BlockedInfoHash, error) {
	rows, err := q.db.Query(ctx, ListBlockedInfoHashes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlockedInfoHash
	for rows.Next() {
		var i BlockedInfoHash
		if err := rows.Scan(&i.InfoHash, &i.Reason, &i.BlockedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpsertBlockedInfoHash = `-- name: UpsertBlockedInfoHash :exec
INSERT INTO blocked_info_hash (info_hash, reason, blocked_at)
VALUES ($1, $2, NOW())
ON CONFLICT (info_hash) DO UPDATE SET
  reason = EXCLUDED.reason
`

type UpsertBlockedInfoHashParams struct {
	InfoHash string
	Reason   string
}

func (q *Queries) UpsertBlockedInfoHash(ctx context.Context, arg UpsertBlockedInfoHashParams) error {
	_, err := q.db.Exec(ctx, UpsertBlockedInfoHash, arg.InfoHash, arg.Reason)
	return err
}
