// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: content.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const GetContent = `-- name: GetContent :one
SELECT type, source, id, title, release_date, adult, overview, popularity, vote_average, vote_count, tsv, created_at, updated_at FROM content WHERE type = $1 AND source = $2 AND id = $3
`

type GetContentParams struct {
	Type   string
	Source string
	ID     string
}

func (q *Queries) GetContent(ctx context.Context, arg GetContentParams) (Content, error) {
	row := q.db.QueryRow(ctx, GetContent, arg.Type, arg.Source, arg.ID)
	var i Content
	err := row.Scan(
		&i.Type,
		&i.Source,
		&i.ID,
		&i.Title,
		&i.ReleaseDate,
		&i.Adult,
		&i.Overview,
		&i.Popularity,
		&i.VoteAverage,
		&i.VoteCount,
		&i.Tsv,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpsertContent = `-- name: UpsertContent :exec
INSERT INTO content (type, source, id, title, release_date, adult,
  overview, popularity, vote_average, vote_count, tsv, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, NOW(), NOW())
ON CONFLICT (type, source, id) DO UPDATE SET
  title = EXCLUDED.title,
  release_date = EXCLUDED.release_date,
  adult = EXCLUDED.adult,
  overview = EXCLUDED.overview,
  popularity = EXCLUDED.popularity,
  vote_average = EXCLUDED.vote_average,
  vote_count = EXCLUDED.vote_count,
  tsv = EXCLUDED.tsv,
  updated_at = NOW()
`

type UpsertContentParams struct {
	Type        string
	Source      string
	ID          string
	Title       string
	ReleaseDate pgtype.Date
	Adult       *bool
	Overview    *string
	Popularity  *float64
	VoteAverage *float64
	VoteCount   *int64
	Tsv         string
}

func (q *Queries) UpsertContent(ctx context.Context, arg UpsertContentParams) error {
	_, err := q.db.Exec(ctx, UpsertContent,
		arg.Type,
		arg.Source,
		arg.ID,
		arg.Title,
		arg.ReleaseDate,
		arg.Adult,
		arg.Overview,
		arg.Popularity,
		arg.VoteAverage,
		arg.VoteCount,
		arg.Tsv,
	)
	return err
}
