// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: key_value.sql

package db

import (
	"context"
)

const GetKeyValue = `-- name: GetKeyValue :one
SELECT key, value, created_at, updated_at FROM key_value WHERE key = $1
`

func (q *Queries) GetKeyValue(ctx context.Context, key string) (KeyValue, error) {
	row := q.db.QueryRow(ctx, GetKeyValue, key)
	var i KeyValue
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpsertKeyValue = `-- name: UpsertKeyValue :exec
INSERT INTO key_value (key, value, created_at, updated_at)
VALUES ($1, $2, NOW(), NOW())
ON CONFLICT (key) DO UPDATE SET
  value = EXCLUDED.value,
  updated_at = NOW()
`

type UpsertKeyValueParams struct {
	Key   string
	Value []byte
}

func (q *Queries) UpsertKeyValue(ctx context.Context, arg UpsertKeyValueParams) error {
	_, err := q.db.Exec(ctx, UpsertKeyValue, arg.Key, arg.Value)
	return err
}
