// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BlockedInfoHash struct {
	InfoHash  string
	Reason    string
	BlockedAt pgtype.Timestamptz
}

type Content struct {
	Type        string
	Source      string
	ID          string
	Title       string
	ReleaseDate pgtype.Date
	Adult       *bool
	Overview    *string
	Popularity  *float64
	VoteAverage *float64
	VoteCount   *int64
	Tsv         string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type KeyValue struct {
	Key       string
	Value     []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Torrent struct {
	InfoHash      string
	Name          string
	Size          int64
	Private       bool
	FilesCount    *int32
	ContentType   *string
	ContentSource *string
	ContentID     *string
	Languages     []byte
	Tsv           string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type TorrentFile struct {
	InfoHash  string
	Index     int32
	PathParts []string
	Extension *string
	Size      int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type TorrentRetryQueue struct {
	InfoHash      string
	Stage         string
	Payload       []byte
	FailCount     int32
	LastError     string
	LastFailureAt pgtype.Timestamptz
	NextRetryAt   pgtype.Timestamptz
	DispatchedAt  pgtype.Timestamptz
}

type TorrentSeeder struct {
	InfoHash  string
	Seeders   *int32
	Leechers  *int32
	UpdatedAt pgtype.Timestamptz
}
