// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: torrents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CountTorrents = `-- name: CountTorrents :one
SELECT COUNT(*) FROM torrents
`

func (q *Queries) CountTorrents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, CountTorrents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountTorrentsBefore = `-- name: CountTorrentsBefore :one
SELECT COUNT(*) FROM torrents WHERE created_at <= $1::timestamptz
`

func (q *Queries) CountTorrentsBefore(ctx context.Context, dollar_1 pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, CountTorrentsBefore, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const DeleteTorrent = `-- name: DeleteTorrent :exec
DELETE FROM torrents WHERE info_hash = $1
`

func (q *Queries) DeleteTorrent(ctx context.Context, infoHash string) error {
	_, err := q.db.Exec(ctx, DeleteTorrent, infoHash)
	return err
}

const GetTorrent = `-- name: GetTorrent :one
SELECT info_hash, name, size, private, files_count, content_type, content_source, content_id, languages, tsv, seeders, leechers, created_at, updated_at FROM torrents WHERE info_hash = $1
`

func (q *Queries) GetTorrent(ctx context.Context, infoHash string) (Torrent, error) {
	row := q.db.QueryRow(ctx, GetTorrent, infoHash)
	var i Torrent
	err := row.Scan(
		&i.InfoHash,
		&i.Name,
		&i.Size,
		&i.Private,
		&i.FilesCount,
		&i.ContentType,
		&i.ContentSource,
		&i.ContentID,
		&i.Languages,
		&i.Tsv,
		&i.Seeders,
		&i.Leechers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListTorrentsByInfoHashes = `-- name: ListTorrentsByInfoHashes :many
SELECT info_hash, name, size, private, files_count, content_type, content_source, content_id, languages, tsv, seeders, leechers, created_at, updated_at FROM torrents WHERE info_hash = ANY($1::text[])
`

func (q *Queries) ListTorrentsByInfoHashes(ctx context.Context, dollar_1 []string) ([]Torrent, error) {
	rows, err := q.db.Query(ctx, ListTorrentsByInfoHashes, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Torrent
	for rows.Next() {
		var i Torrent
		if err := rows.Scan(
			&i.InfoHash,
			&i.Name,
			&i.Size,
			&i.Private,
			&i.FilesCount,
			&i.ContentType,
			&i.ContentSource,
			&i.ContentID,
			&i.Languages,
			&i.Tsv,
			&i.Seeders,
			&i.Leechers,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListTorrentsPaginated = `-- name: ListTorrentsPaginated :many
SELECT info_hash, name, size, private, files_count, content_type, content_source, content_id, languages, tsv, seeders, leechers, created_at, updated_at FROM torrents ORDER BY created_at LIMIT $1 OFFSET $2
`

type ListTorrentsPaginatedParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListTorrentsPaginated(ctx context.Context, arg ListTorrentsPaginatedParams) ([]Torrent, error) {
	rows, err := q.db.Query(ctx, ListTorrentsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Torrent
	for rows.Next() {
		var i Torrent
		if err := rows.Scan(
			&i.InfoHash,
			&i.Name,
			&i.Size,
			&i.Private,
			&i.FilesCount,
			&i.ContentType,
			&i.ContentSource,
			&i.ContentID,
			&i.Languages,
			&i.Tsv,
			&i.Seeders,
			&i.Leechers,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListTorrentsPaginatedBefore = `-- name: ListTorrentsPaginatedBefore :many
SELECT info_hash, name, size, private, files_count, content_type, content_source, content_id, languages, tsv, seeders, leechers, created_at, updated_at FROM torrents WHERE created_at <= $1::timestamptz ORDER BY created_at LIMIT $2 OFFSET $3
`

type ListTorrentsPaginatedBeforeParams struct {
	Column1 pgtype.Timestamptz
	Limit   int32
	Offset  int32
}

func (q *Queries) ListTorrentsPaginatedBefore(ctx context.Context, arg ListTorrentsPaginatedBeforeParams) ([]Torrent, error) {
	rows, err := q.db.Query(ctx, ListTorrentsPaginatedBefore, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Torrent
	for rows.Next() {
		var i Torrent
		if err := rows.Scan(
			&i.InfoHash,
			&i.Name,
			&i.Size,
			&i.Private,
			&i.FilesCount,
			&i.ContentType,
			&i.ContentSource,
			&i.ContentID,
			&i.Languages,
			&i.Tsv,
			&i.Seeders,
			&i.Leechers,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateTorrentContent = `-- name: UpdateTorrentContent :exec
UPDATE torrents SET
  content_type = $2,
  content_source = $3,
  content_id = $4,
  languages = $5,
  tsv = $6,
  updated_at = NOW()
WHERE info_hash = $1
`

type UpdateTorrentContentParams struct {
	InfoHash      string
	ContentType   *string
	ContentSource *string
	ContentID     *string
	Languages     []byte
	Tsv           string
}

func (q *Queries) UpdateTorrentContent(ctx context.Context, arg UpdateTorrentContentParams) error {
	_, err := q.db.Exec(ctx, UpdateTorrentContent,
		arg.InfoHash,
		arg.ContentType,
		arg.ContentSource,
		arg.ContentID,
		arg.Languages,
		arg.Tsv,
	)
	return err
}

const UpdateTorrentSeeders = `-- name: UpdateTorrentSeeders :exec
UPDATE torrents SET
  seeders = GREATEST(torrents.seeders, $2),
  leechers = GREATEST(torrents.leechers, $3),
  updated_at = NOW()
WHERE info_hash = $1
`

type UpdateTorrentSeedersParams struct {
	InfoHash string
	Seeders  *int32
	Leechers *int32
}

func (q *Queries) UpdateTorrentSeeders(ctx context.Context, arg UpdateTorrentSeedersParams) error {
	_, err := q.db.Exec(ctx, UpdateTorrentSeeders, arg.InfoHash, arg.Seeders, arg.Leechers)
	return err
}

const UpsertTorrent = `-- name: UpsertTorrent :exec
INSERT INTO torrents (info_hash, name, size, private, files_count, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
ON CONFLICT (info_hash) DO UPDATE SET
  name = EXCLUDED.name,
  size = EXCLUDED.size,
  private = EXCLUDED.private,
  files_count = EXCLUDED.files_count,
  updated_at = NOW()
`

type UpsertTorrentParams struct {
	InfoHash   string
	Name       string
	Size       int64
	Private    bool
	FilesCount *int32
}

func (q *Queries) UpsertTorrent(ctx context.Context, arg UpsertTorrentParams) error {
	_, err := q.db.Exec(ctx, UpsertTorrent,
		arg.InfoHash,
		arg.Name,
		arg.Size,
		arg.Private,
		arg.FilesCount,
	)
	return err
}
