// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: torrent_retry_queue.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const BackoffTorrentRetryBatch = `-- name: BackoffTorrentRetryBatch :exec
UPDATE torrent_retry_queue t
SET next_retry_at = NOW() + make_interval(secs => d.delay_secs)
FROM (
  SELECT unnest($1::text[]) AS info_hash,
         unnest($2::text[]) AS stage,
         unnest($3::int[]) AS delay_secs
) d
WHERE t.info_hash = d.info_hash AND t.stage = d.stage
`

type BackoffTorrentRetryBatchParams struct {
	InfoHashes []string
	Stages     []string
	DelaySecs  []int32
}

func (q *Queries) BackoffTorrentRetryBatch(ctx context.Context, arg BackoffTorrentRetryBatchParams) error {
	_, err := q.db.Exec(ctx, BackoffTorrentRetryBatch, arg.InfoHashes, arg.Stages, arg.DelaySecs)
	return err
}

const ClearTorrentRetryQueue = `-- name: ClearTorrentRetryQueue :exec
DELETE FROM torrent_retry_queue
`

func (q *Queries) ClearTorrentRetryQueue(ctx context.Context) error {
	_, err := q.db.Exec(ctx, ClearTorrentRetryQueue)
	return err
}

const CountTorrentRetryQueue = `-- name: CountTorrentRetryQueue :one
SELECT COUNT(*) FROM torrent_retry_queue
`

func (q *Queries) CountTorrentRetryQueue(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, CountTorrentRetryQueue)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const DeleteTorrentRetry = `-- name: DeleteTorrentRetry :exec
DELETE FROM torrent_retry_queue WHERE info_hash = $1
`

func (q *Queries) DeleteTorrentRetry(ctx context.Context, infoHash string) error {
	_, err := q.db.Exec(ctx, DeleteTorrentRetry, infoHash)
	return err
}

const ListDueTorrentRetry = `-- name: ListDueTorrentRetry :many
SELECT info_hash, stage, payload, fail_count, last_error, last_failure_at, next_retry_at, dispatched_at FROM torrent_retry_queue
WHERE next_retry_at <= NOW()
ORDER BY next_retry_at
LIMIT $1
`

func (q *Queries) ListDueTorrentRetry(ctx context.Context, limit int32) ([]TorrentRetryQueue, error) {
	rows, err := q.db.Query(ctx, ListDueTorrentRetry, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TorrentRetryQueue
	for rows.Next() {
		var i TorrentRetryQueue
		if err := rows.Scan(
			&i.InfoHash,
			&i.Stage,
			&i.Payload,
			&i.FailCount,
			&i.LastError,
			&i.LastFailureAt,
			&i.NextRetryAt,
			&i.DispatchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListTorrentRetryQueue = `-- name: ListTorrentRetryQueue :many
SELECT info_hash, stage, payload, fail_count, last_error, last_failure_at, next_retry_at, dispatched_at FROM torrent_retry_queue
ORDER BY next_retry_at
LIMIT $1 OFFSET $2
`

type ListTorrentRetryQueueParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListTorrentRetryQueue(ctx context.Context, arg ListTorrentRetryQueueParams) ([]TorrentRetryQueue, error) {
	rows, err := q.db.Query(ctx, ListTorrentRetryQueue, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TorrentRetryQueue
	for rows.Next() {
		var i TorrentRetryQueue
		if err := rows.Scan(
			&i.InfoHash,
			&i.Stage,
			&i.Payload,
			&i.FailCount,
			&i.LastError,
			&i.LastFailureAt,
			&i.NextRetryAt,
			&i.DispatchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const MarkTorrentRetryDispatched = `-- name: MarkTorrentRetryDispatched :exec
UPDATE torrent_retry_queue
SET next_retry_at = $1,
    dispatched_at = NOW(),
    fail_count = $2
WHERE info_hash = $3 AND stage = $4
`

type MarkTorrentRetryDispatchedParams struct {
	NextRetryAt pgtype.Timestamptz
	FailCount   int32
	InfoHash    string
	Stage       string
}

func (q *Queries) MarkTorrentRetryDispatched(ctx context.Context, arg MarkTorrentRetryDispatchedParams) error {
	_, err := q.db.Exec(ctx, MarkTorrentRetryDispatched,
		arg.NextRetryAt,
		arg.FailCount,
		arg.InfoHash,
		arg.Stage,
	)
	return err
}

const TouchTorrentRetry = `-- name: TouchTorrentRetry :execrows
UPDATE torrent_retry_queue
SET next_retry_at = NOW(),
    dispatched_at = NULL
WHERE info_hash = $1
`

func (q *Queries) TouchTorrentRetry(ctx context.Context, infoHash string) (int64, error) {
	result, err := q.db.Exec(ctx, TouchTorrentRetry, infoHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const UpsertTorrentRetryBatch = `-- name: UpsertTorrentRetryBatch :many
INSERT INTO torrent_retry_queue (info_hash, stage, payload, fail_count, last_error, last_failure_at, next_retry_at, dispatched_at)
SELECT
  unnest($1::text[]),
  unnest($2::text[]),
  unnest($3::jsonb[]),
  1,
  unnest($4::text[]),
  NOW(),
  NOW(),
  NULL
ON CONFLICT (info_hash, stage) DO UPDATE SET
  payload = EXCLUDED.payload,
  fail_count = torrent_retry_queue.fail_count + 1,
  last_error = EXCLUDED.last_error,
  last_failure_at = NOW(),
  dispatched_at = NULL
RETURNING info_hash, stage, fail_count
`

type UpsertTorrentRetryBatchParams struct {
	InfoHashes []string
	Stages     []string
	Payloads   [][]byte
	LastErrors []string
}

type UpsertTorrentRetryBatchRow struct {
	InfoHash  string
	Stage     string
	FailCount int32
}

func (q *Queries) UpsertTorrentRetryBatch(ctx context.Context, arg UpsertTorrentRetryBatchParams) ([]UpsertTorrentRetryBatchRow, error) {
	rows, err := q.db.Query(ctx, UpsertTorrentRetryBatch,
		arg.InfoHashes,
		arg.Stages,
		arg.Payloads,
		arg.LastErrors,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UpsertTorrentRetryBatchRow
	for rows.Next() {
		var i UpsertTorrentRetryBatchRow
		if err := rows.Scan(&i.InfoHash, &i.Stage, &i.FailCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
