// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: torrents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CountTorrents = `-- name: CountTorrents :one
SELECT COUNT(*) FROM torrents
`

func (q *Queries) CountTorrents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, CountTorrents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountTorrentsBefore = `-- name: CountTorrentsBefore :one
SELECT COUNT(*) FROM torrents WHERE created_at <= $1::timestamptz
`

func (q *Queries) CountTorrentsBefore(ctx context.Context, dollar_1 pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, CountTorrentsBefore, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const DeleteTorrent = `-- name: DeleteTorrent :exec
DELETE FROM torrents WHERE info_hash = $1
`

func (q *Queries) DeleteTorrent(ctx context.Context, infoHash string) error {
	_, err := q.db.Exec(ctx, DeleteTorrent, infoHash)
	return err
}

const GetTorrent = `-- name: GetTorrent :one
SELECT t.info_hash, t.name, t.size, t.private, t.files_count, t.content_type, t.content_source, t.content_id, t.languages, t.tsv, t.created_at, t.updated_at, s.seeders, s.leechers
FROM torrents t
LEFT JOIN torrent_seeders s ON s.info_hash = t.info_hash
WHERE t.info_hash = $1
`

type GetTorrentRow struct {
	Torrent  Torrent
	Seeders  *int32
	Leechers *int32
}

func (q *Queries) GetTorrent(ctx context.Context, infoHash string) (GetTorrentRow, error) {
	row := q.db.QueryRow(ctx, GetTorrent, infoHash)
	var i GetTorrentRow
	err := row.Scan(
		&i.Torrent.InfoHash,
		&i.Torrent.Name,
		&i.Torrent.Size,
		&i.Torrent.Private,
		&i.Torrent.FilesCount,
		&i.Torrent.ContentType,
		&i.Torrent.ContentSource,
		&i.Torrent.ContentID,
		&i.Torrent.Languages,
		&i.Torrent.Tsv,
		&i.Torrent.CreatedAt,
		&i.Torrent.UpdatedAt,
		&i.Seeders,
		&i.Leechers,
	)
	return i, err
}

const ListTorrentsByInfoHashes = `-- name: ListTorrentsByInfoHashes :many
SELECT t.info_hash, t.name, t.size, t.private, t.files_count, t.content_type, t.content_source, t.content_id, t.languages, t.tsv, t.created_at, t.updated_at, s.seeders, s.leechers
FROM torrents t
LEFT JOIN torrent_seeders s ON s.info_hash = t.info_hash
WHERE t.info_hash = ANY($1::text[])
`

type ListTorrentsByInfoHashesRow struct {
	Torrent  Torrent
	Seeders  *int32
	Leechers *int32
}

func (q *Queries) ListTorrentsByInfoHashes(ctx context.Context, dollar_1 []string) ([]ListTorrentsByInfoHashesRow, error) {
	rows, err := q.db.Query(ctx, ListTorrentsByInfoHashes, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTorrentsByInfoHashesRow
	for rows.Next() {
		var i ListTorrentsByInfoHashesRow
		if err := rows.Scan(
			&i.Torrent.InfoHash,
			&i.Torrent.Name,
			&i.Torrent.Size,
			&i.Torrent.Private,
			&i.Torrent.FilesCount,
			&i.Torrent.ContentType,
			&i.Torrent.ContentSource,
			&i.Torrent.ContentID,
			&i.Torrent.Languages,
			&i.Torrent.Tsv,
			&i.Torrent.CreatedAt,
			&i.Torrent.UpdatedAt,
			&i.Seeders,
			&i.Leechers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListTorrentsPageAfter = `-- name: ListTorrentsPageAfter :many
SELECT t.info_hash, t.name, t.size, t.private, t.files_count, t.content_type, t.content_source, t.content_id, t.languages, t.tsv, t.created_at, t.updated_at, s.seeders, s.leechers
FROM torrents t
LEFT JOIN torrent_seeders s ON s.info_hash = t.info_hash
WHERE t.created_at <= $1::timestamptz
  AND (t.created_at, t.info_hash) > ($2::timestamptz, $3::text)
ORDER BY t.created_at, t.info_hash
LIMIT $4
`

type ListTorrentsPageAfterParams struct {
	BarrierTime     pgtype.Timestamptz
	CursorCreatedAt pgtype.Timestamptz
	CursorInfoHash  string
	BatchSize       int32
}

type ListTorrentsPageAfterRow struct {
	Torrent  Torrent
	Seeders  *int32
	Leechers *int32
}

func (q *Queries) ListTorrentsPageAfter(ctx context.Context, arg ListTorrentsPageAfterParams) ([]ListTorrentsPageAfterRow, error) {
	rows, err := q.db.Query(ctx, ListTorrentsPageAfter,
		arg.BarrierTime,
		arg.CursorCreatedAt,
		arg.CursorInfoHash,
		arg.BatchSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTorrentsPageAfterRow
	for rows.Next() {
		var i ListTorrentsPageAfterRow
		if err := rows.Scan(
			&i.Torrent.InfoHash,
			&i.Torrent.Name,
			&i.Torrent.Size,
			&i.Torrent.Private,
			&i.Torrent.FilesCount,
			&i.Torrent.ContentType,
			&i.Torrent.ContentSource,
			&i.Torrent.ContentID,
			&i.Torrent.Languages,
			&i.Torrent.Tsv,
			&i.Torrent.CreatedAt,
			&i.Torrent.UpdatedAt,
			&i.Seeders,
			&i.Leechers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListTorrentsPaginated = `-- name: ListTorrentsPaginated :many
SELECT t.info_hash, t.name, t.size, t.private, t.files_count, t.content_type, t.content_source, t.content_id, t.languages, t.tsv, t.created_at, t.updated_at, s.seeders, s.leechers
FROM torrents t
LEFT JOIN torrent_seeders s ON s.info_hash = t.info_hash
ORDER BY t.created_at LIMIT $1 OFFSET $2
`

type ListTorrentsPaginatedParams struct {
	Limit  int32
	Offset int32
}

type ListTorrentsPaginatedRow struct {
	Torrent  Torrent
	Seeders  *int32
	Leechers *int32
}

func (q *Queries) ListTorrentsPaginated(ctx context.Context, arg ListTorrentsPaginatedParams) ([]ListTorrentsPaginatedRow, error) {
	rows, err := q.db.Query(ctx, ListTorrentsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTorrentsPaginatedRow
	for rows.Next() {
		var i ListTorrentsPaginatedRow
		if err := rows.Scan(
			&i.Torrent.InfoHash,
			&i.Torrent.Name,
			&i.Torrent.Size,
			&i.Torrent.Private,
			&i.Torrent.FilesCount,
			&i.Torrent.ContentType,
			&i.Torrent.ContentSource,
			&i.Torrent.ContentID,
			&i.Torrent.Languages,
			&i.Torrent.Tsv,
			&i.Torrent.CreatedAt,
			&i.Torrent.UpdatedAt,
			&i.Seeders,
			&i.Leechers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListTorrentsPaginatedBefore = `-- name: ListTorrentsPaginatedBefore :many
SELECT t.info_hash, t.name, t.size, t.private, t.files_count, t.content_type, t.content_source, t.content_id, t.languages, t.tsv, t.created_at, t.updated_at, s.seeders, s.leechers
FROM torrents t
LEFT JOIN torrent_seeders s ON s.info_hash = t.info_hash
WHERE t.created_at <= $1::timestamptz ORDER BY t.created_at LIMIT $2 OFFSET $3
`

type ListTorrentsPaginatedBeforeParams struct {
	Column1 pgtype.Timestamptz
	Limit   int32
	Offset  int32
}

type ListTorrentsPaginatedBeforeRow struct {
	Torrent  Torrent
	Seeders  *int32
	Leechers *int32
}

func (q *Queries) ListTorrentsPaginatedBefore(ctx context.Context, arg ListTorrentsPaginatedBeforeParams) ([]ListTorrentsPaginatedBeforeRow, error) {
	rows, err := q.db.Query(ctx, ListTorrentsPaginatedBefore, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTorrentsPaginatedBeforeRow
	for rows.Next() {
		var i ListTorrentsPaginatedBeforeRow
		if err := rows.Scan(
			&i.Torrent.InfoHash,
			&i.Torrent.Name,
			&i.Torrent.Size,
			&i.Torrent.Private,
			&i.Torrent.FilesCount,
			&i.Torrent.ContentType,
			&i.Torrent.ContentSource,
			&i.Torrent.ContentID,
			&i.Torrent.Languages,
			&i.Torrent.Tsv,
			&i.Torrent.CreatedAt,
			&i.Torrent.UpdatedAt,
			&i.Seeders,
			&i.Leechers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateTorrentContent = `-- name: UpdateTorrentContent :exec
UPDATE torrents SET
  content_type = $2,
  content_source = $3,
  content_id = $4,
  languages = $5,
  tsv = $6,
  updated_at = NOW()
WHERE info_hash = $1
`

type UpdateTorrentContentParams struct {
	InfoHash      string
	ContentType   *string
	ContentSource *string
	ContentID     *string
	Languages     []byte
	Tsv           string
}

func (q *Queries) UpdateTorrentContent(ctx context.Context, arg UpdateTorrentContentParams) error {
	_, err := q.db.Exec(ctx, UpdateTorrentContent,
		arg.InfoHash,
		arg.ContentType,
		arg.ContentSource,
		arg.ContentID,
		arg.Languages,
		arg.Tsv,
	)
	return err
}

const UpdateTorrentSeeders = `-- name: UpdateTorrentSeeders :exec
INSERT INTO torrent_seeders (info_hash, seeders, leechers, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (info_hash) DO UPDATE SET
  seeders = GREATEST(torrent_seeders.seeders, EXCLUDED.seeders),
  leechers = GREATEST(torrent_seeders.leechers, EXCLUDED.leechers),
  updated_at = NOW()
`

type UpdateTorrentSeedersParams struct {
	InfoHash string
	Seeders  *int32
	Leechers *int32
}

func (q *Queries) UpdateTorrentSeeders(ctx context.Context, arg UpdateTorrentSeedersParams) error {
	_, err := q.db.Exec(ctx, UpdateTorrentSeeders, arg.InfoHash, arg.Seeders, arg.Leechers)
	return err
}

const UpsertTorrent = `-- name: UpsertTorrent :exec
INSERT INTO torrents (info_hash, name, size, private, files_count, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
ON CONFLICT (info_hash) DO UPDATE SET
  name = EXCLUDED.name,
  size = EXCLUDED.size,
  private = EXCLUDED.private,
  files_count = EXCLUDED.files_count,
  updated_at = NOW()
`

type UpsertTorrentParams struct {
	InfoHash   string
	Name       string
	Size       int64
	Private    bool
	FilesCount *int32
}

func (q *Queries) UpsertTorrent(ctx context.Context, arg UpsertTorrentParams) error {
	_, err := q.db.Exec(ctx, UpsertTorrent,
		arg.InfoHash,
		arg.Name,
		arg.Size,
		arg.Private,
		arg.FilesCount,
	)
	return err
}
