// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: torrent_files.sql

package db

import (
	"context"
)

const CountTorrentFiles = `-- name: CountTorrentFiles :one
SELECT COUNT(*) FROM torrent_files WHERE info_hash = $1
`

func (q *Queries) CountTorrentFiles(ctx context.Context, infoHash string) (int64, error) {
	row := q.db.QueryRow(ctx, CountTorrentFiles, infoHash)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const ListTorrentFiles = `-- name: ListTorrentFiles :many
SELECT info_hash, index, path_parts, extension, size, created_at, updated_at FROM torrent_files WHERE info_hash = $1 ORDER BY "index"
`

func (q *Queries) ListTorrentFiles(ctx context.Context, infoHash string) ([]TorrentFile, error) {
	rows, err := q.db.Query(ctx, ListTorrentFiles, infoHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TorrentFile
	for rows.Next() {
		var i TorrentFile
		if err := rows.Scan(
			&i.InfoHash,
			&i.Index,
			&i.PathParts,
			&i.Extension,
			&i.Size,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListTorrentFilesPaginated = `-- name: ListTorrentFilesPaginated :many
SELECT info_hash, index, path_parts, extension, size, created_at, updated_at FROM torrent_files WHERE info_hash = $1 ORDER BY "index" LIMIT $2 OFFSET $3
`

type ListTorrentFilesPaginatedParams struct {
	InfoHash string
	Limit    int32
	Offset   int32
}

func (q *Queries) ListTorrentFilesPaginated(ctx context.Context, arg ListTorrentFilesPaginatedParams) ([]TorrentFile, error) {
	rows, err := q.db.Query(ctx, ListTorrentFilesPaginated, arg.InfoHash, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TorrentFile
	for rows.Next() {
		var i TorrentFile
		if err := rows.Scan(
			&i.InfoHash,
			&i.Index,
			&i.PathParts,
			&i.Extension,
			&i.Size,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const TorrentFileExists = `-- name: TorrentFileExists :one
SELECT EXISTS(SELECT 1 FROM torrent_files WHERE info_hash = $1 OFFSET $2)
`

type TorrentFileExistsParams struct {
	InfoHash string
	Offset   int32
}

func (q *Queries) TorrentFileExists(ctx context.Context, arg TorrentFileExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, TorrentFileExists, arg.InfoHash, arg.Offset)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const UpsertTorrentFile = `-- name: UpsertTorrentFile :exec
INSERT INTO torrent_files (info_hash, "index", path_parts, size, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
ON CONFLICT (info_hash, "index") DO UPDATE SET
  path_parts = EXCLUDED.path_parts,
  size = EXCLUDED.size,
  updated_at = NOW()
`

type UpsertTorrentFileParams struct {
	InfoHash  string
	Index     int32
	PathParts []string
	Size      int64
}

func (q *Queries) UpsertTorrentFile(ctx context.Context, arg UpsertTorrentFileParams) error {
	_, err := q.db.Exec(ctx, UpsertTorrentFile,
		arg.InfoHash,
		arg.Index,
		arg.PathParts,
		arg.Size,
	)
	return err
}
