// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package tmdb_mocks

import (
	"context"

	"github.com/hexsans/hexmagnet/internal/tmdb"
	mock "github.com/stretchr/testify/mock"
)

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// MovieDetails provides a mock function for the type Client
func (_mock *Client) MovieDetails(ctx context.Context, request tmdb.MovieDetailsRequest) (tmdb.MovieDetailsResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for MovieDetails")
	}

	var r0 tmdb.MovieDetailsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, tmdb.MovieDetailsRequest) (tmdb.MovieDetailsResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, tmdb.MovieDetailsRequest) tmdb.MovieDetailsResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(tmdb.MovieDetailsResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, tmdb.MovieDetailsRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_MovieDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MovieDetails'
type Client_MovieDetails_Call struct {
	*mock.Call
}

// MovieDetails is a helper method to define mock.On call
//   - ctx context.Context
//   - request tmdb.MovieDetailsRequest
func (_e *Client_Expecter) MovieDetails(ctx any, request any) *Client_MovieDetails_Call {
	return &Client_MovieDetails_Call{Call: _e.mock.On("MovieDetails", ctx, request)}
}

func (_c *Client_MovieDetails_Call) Run(run func(ctx context.Context, request tmdb.MovieDetailsRequest)) *Client_MovieDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 tmdb.MovieDetailsRequest
		if args[1] != nil {
			arg1 = args[1].(tmdb.MovieDetailsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_MovieDetails_Call) Return(movieDetailsResponse tmdb.MovieDetailsResponse, err error) *Client_MovieDetails_Call {
	_c.Call.Return(movieDetailsResponse, err)
	return _c
}

func (_c *Client_MovieDetails_Call) RunAndReturn(run func(ctx context.Context, request tmdb.MovieDetailsRequest) (tmdb.MovieDetailsResponse, error)) *Client_MovieDetails_Call {
	_c.Call.Return(run)
	return _c
}

// SearchMovie provides a mock function for the type Client
func (_mock *Client) SearchMovie(ctx context.Context, request tmdb.SearchMovieRequest) (tmdb.SearchMovieResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for SearchMovie")
	}

	var r0 tmdb.SearchMovieResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, tmdb.SearchMovieRequest) (tmdb.SearchMovieResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, tmdb.SearchMovieRequest) tmdb.SearchMovieResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(tmdb.SearchMovieResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, tmdb.SearchMovieRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_SearchMovie_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchMovie'
type Client_SearchMovie_Call struct {
	*mock.Call
}

// SearchMovie is a helper method to define mock.On call
//   - ctx context.Context
//   - request tmdb.SearchMovieRequest
func (_e *Client_Expecter) SearchMovie(ctx any, request any) *Client_SearchMovie_Call {
	return &Client_SearchMovie_Call{Call: _e.mock.On("SearchMovie", ctx, request)}
}

func (_c *Client_SearchMovie_Call) Run(run func(ctx context.Context, request tmdb.SearchMovieRequest)) *Client_SearchMovie_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 tmdb.SearchMovieRequest
		if args[1] != nil {
			arg1 = args[1].(tmdb.SearchMovieRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_SearchMovie_Call) Return(searchMovieResponse tmdb.SearchMovieResponse, err error) *Client_SearchMovie_Call {
	_c.Call.Return(searchMovieResponse, err)
	return _c
}

func (_c *Client_SearchMovie_Call) RunAndReturn(run func(ctx context.Context, request tmdb.SearchMovieRequest) (tmdb.SearchMovieResponse, error)) *Client_SearchMovie_Call {
	_c.Call.Return(run)
	return _c
}

// SearchTv provides a mock function for the type Client
func (_mock *Client) SearchTv(ctx context.Context, request tmdb.SearchTvRequest) (tmdb.SearchTvResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for SearchTv")
	}

	var r0 tmdb.SearchTvResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, tmdb.SearchTvRequest) (tmdb.SearchTvResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, tmdb.SearchTvRequest) tmdb.SearchTvResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(tmdb.SearchTvResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, tmdb.SearchTvRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_SearchTv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchTv'
type Client_SearchTv_Call struct {
	*mock.Call
}

// SearchTv is a helper method to define mock.On call
//   - ctx context.Context
//   - request tmdb.SearchTvRequest
func (_e *Client_Expecter) SearchTv(ctx any, request any) *Client_SearchTv_Call {
	return &Client_SearchTv_Call{Call: _e.mock.On("SearchTv", ctx, request)}
}

func (_c *Client_SearchTv_Call) Run(run func(ctx context.Context, request tmdb.SearchTvRequest)) *Client_SearchTv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 tmdb.SearchTvRequest
		if args[1] != nil {
			arg1 = args[1].(tmdb.SearchTvRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_SearchTv_Call) Return(searchTvResponse tmdb.SearchTvResponse, err error) *Client_SearchTv_Call {
	_c.Call.Return(searchTvResponse, err)
	return _c
}

func (_c *Client_SearchTv_Call) RunAndReturn(run func(ctx context.Context, request tmdb.SearchTvRequest) (tmdb.SearchTvResponse, error)) *Client_SearchTv_Call {
	_c.Call.Return(run)
	return _c
}

// TvDetails provides a mock function for the type Client
func (_mock *Client) TvDetails(ctx context.Context, request tmdb.TvDetailsRequest) (tmdb.TvDetailsResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for TvDetails")
	}

	var r0 tmdb.TvDetailsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, tmdb.TvDetailsRequest) (tmdb.TvDetailsResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, tmdb.TvDetailsRequest) tmdb.TvDetailsResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(tmdb.TvDetailsResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, tmdb.TvDetailsRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_TvDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TvDetails'
type Client_TvDetails_Call struct {
	*mock.Call
}

// TvDetails is a helper method to define mock.On call
//   - ctx context.Context
//   - request tmdb.TvDetailsRequest
func (_e *Client_Expecter) TvDetails(ctx any, request any) *Client_TvDetails_Call {
	return &Client_TvDetails_Call{Call: _e.mock.On("TvDetails", ctx, request)}
}

func (_c *Client_TvDetails_Call) Run(run func(ctx context.Context, request tmdb.TvDetailsRequest)) *Client_TvDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 tmdb.TvDetailsRequest
		if args[1] != nil {
			arg1 = args[1].(tmdb.TvDetailsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_TvDetails_Call) Return(tvDetailsResponse tmdb.TvDetailsResponse, err error) *Client_TvDetails_Call {
	_c.Call.Return(tvDetailsResponse, err)
	return _c
}

func (_c *Client_TvDetails_Call) RunAndReturn(run func(ctx context.Context, request tmdb.TvDetailsRequest) (tmdb.TvDetailsResponse, error)) *Client_TvDetails_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAccessToken provides a mock function for the type Client
func (_mock *Client) ValidateAccessToken(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccessToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_ValidateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAccessToken'
type Client_ValidateAccessToken_Call struct {
	*mock.Call
}

// ValidateAccessToken is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Client_Expecter) ValidateAccessToken(ctx any) *Client_ValidateAccessToken_Call {
	return &Client_ValidateAccessToken_Call{Call: _e.mock.On("ValidateAccessToken", ctx)}
}

func (_c *Client_ValidateAccessToken_Call) Run(run func(ctx context.Context)) *Client_ValidateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Client_ValidateAccessToken_Call) Return(err error) *Client_ValidateAccessToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_ValidateAccessToken_Call) RunAndReturn(run func(ctx context.Context) error) *Client_ValidateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}
