// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/hexsans/hexmagnet/internal/database/fts"
)

const TableNameContent = "content"

// Content mapped from table <content>
type Content struct {
	Type        ContentType  `gorm:"column:type;primaryKey;<-:create" json:"type"`
	Source      string       `gorm:"column:source;primaryKey;<-:create" json:"source"`
	ID          string       `gorm:"column:id;primaryKey;<-:create" json:"id"`
	Title       string       `gorm:"column:title;not null" json:"title"`
	ReleaseDate Date         `gorm:"column:release_date" json:"releaseDate"`
	Adult       NullBool     `gorm:"column:adult" json:"adult"`
	Overview    NullString   `gorm:"column:overview" json:"overview"`
	Popularity  NullFloat32  `gorm:"column:popularity" json:"popularity"`
	VoteAverage NullFloat32  `gorm:"column:vote_average" json:"voteAverage"`
	VoteCount   NullUint     `gorm:"column:vote_count" json:"voteCount"`
	CreatedAt   time.Time    `gorm:"column:created_at;not null;<-:create" json:"createdAt"`
	UpdatedAt   time.Time    `gorm:"column:updated_at;not null" json:"updatedAt"`
	Tsv         fts.Tsvector `gorm:"column:tsv" json:"tsv"`
}

// TableName Content's table name
func (*Content) TableName() string {
	return TableNameContent
}
