// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package classifier_mocks

import (
	"context"

	"github.com/hexsans/hexmagnet/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewLocalSearch creates a new instance of LocalSearch. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLocalSearch(t interface {
	mock.TestingT
	Cleanup(func())
}) *LocalSearch {
	mock := &LocalSearch{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// LocalSearch is an autogenerated mock type for the LocalSearch type
type LocalSearch struct {
	mock.Mock
}

type LocalSearch_Expecter struct {
	mock *mock.Mock
}

func (_m *LocalSearch) EXPECT() *LocalSearch_Expecter {
	return &LocalSearch_Expecter{mock: &_m.Mock}
}

// ContentByID provides a mock function for the type LocalSearch
func (_mock *LocalSearch) ContentByID(context1 context.Context, contentRef model.ContentRef) (model.Content, error) {
	ret := _mock.Called(context1, contentRef)

	if len(ret) == 0 {
		panic("no return value specified for ContentByID")
	}

	var r0 model.Content
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ContentRef) (model.Content, error)); ok {
		return returnFunc(context1, contentRef)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ContentRef) model.Content); ok {
		r0 = returnFunc(context1, contentRef)
	} else {
		r0 = ret.Get(0).(model.Content)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.ContentRef) error); ok {
		r1 = returnFunc(context1, contentRef)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LocalSearch_ContentByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContentByID'
type LocalSearch_ContentByID_Call struct {
	*mock.Call
}

// ContentByID is a helper method to define mock.On call
//   - context1 context.Context
//   - contentRef model.ContentRef
func (_e *LocalSearch_Expecter) ContentByID(context1 any, contentRef any) *LocalSearch_ContentByID_Call {
	return &LocalSearch_ContentByID_Call{Call: _e.mock.On("ContentByID", context1, contentRef)}
}

func (_c *LocalSearch_ContentByID_Call) Run(run func(context1 context.Context, contentRef model.ContentRef)) *LocalSearch_ContentByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.ContentRef
		if args[1] != nil {
			arg1 = args[1].(model.ContentRef)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LocalSearch_ContentByID_Call) Return(content model.Content, err error) *LocalSearch_ContentByID_Call {
	_c.Call.Return(content, err)
	return _c
}

func (_c *LocalSearch_ContentByID_Call) RunAndReturn(run func(context1 context.Context, contentRef model.ContentRef) (model.Content, error)) *LocalSearch_ContentByID_Call {
	_c.Call.Return(run)
	return _c
}

// ContentBySearch provides a mock function for the type LocalSearch
func (_mock *LocalSearch) ContentBySearch(context1 context.Context, contentType model.ContentType, s string, year model.Year) (model.Content, error) {
	ret := _mock.Called(context1, contentType, s, year)

	if len(ret) == 0 {
		panic("no return value specified for ContentBySearch")
	}

	var r0 model.Content
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ContentType, string, model.Year) (model.Content, error)); ok {
		return returnFunc(context1, contentType, s, year)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ContentType, string, model.Year) model.Content); ok {
		r0 = returnFunc(context1, contentType, s, year)
	} else {
		r0 = ret.Get(0).(model.Content)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.ContentType, string, model.Year) error); ok {
		r1 = returnFunc(context1, contentType, s, year)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LocalSearch_ContentBySearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContentBySearch'
type LocalSearch_ContentBySearch_Call struct {
	*mock.Call
}

// ContentBySearch is a helper method to define mock.On call
//   - context1 context.Context
//   - contentType model.ContentType
//   - s string
//   - year model.Year
func (_e *LocalSearch_Expecter) ContentBySearch(context1 any, contentType any, s any, year any) *LocalSearch_ContentBySearch_Call {
	return &LocalSearch_ContentBySearch_Call{Call: _e.mock.On("ContentBySearch", context1, contentType, s, year)}
}

func (_c *LocalSearch_ContentBySearch_Call) Run(run func(context1 context.Context, contentType model.ContentType, s string, year model.Year)) *LocalSearch_ContentBySearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.ContentType
		if args[1] != nil {
			arg1 = args[1].(model.ContentType)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 model.Year
		if args[3] != nil {
			arg3 = args[3].(model.Year)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *LocalSearch_ContentBySearch_Call) Return(content model.Content, err error) *LocalSearch_ContentBySearch_Call {
	_c.Call.Return(content, err)
	return _c
}

func (_c *LocalSearch_ContentBySearch_Call) RunAndReturn(run func(context1 context.Context, contentType model.ContentType, s string, year model.Year) (model.Content, error)) *LocalSearch_ContentBySearch_Call {
	_c.Call.Return(run)
	return _c
}
