name: Checks

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: webui/package-lock.json

      - name: Run webui lint and typecheck
        run: cd webui && npm ci --prefer-offline && npm run lint && npm run typecheck

      - name: Create dummy webui dist
        run: |
          mkdir -p webui/dist
          touch webui/dist/index.html

      - name: Run golangci lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12
          args: --timeout=10m

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - name: Run tests
        run: |
          mkdir -p webui/dist
          touch webui/dist/index.html
          go test -count=1 -timeout 180s -v ./internal/...

  # Generate code and build again
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: webui/package-lock.json
      - name: Install webui dependencies
        run: cd webui && npm ci --prefer-offline
      - name: Build web app
        run: make gen-webui-graphql && make build-webui
      - name: Build golang app
        run: make gen-go gen-schema gen-sqlc gen-gql-enums gen-gql && make build-go

